config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  resources :products
  resources :orders
  resources :customers
  #get 'home/index'
  get 'home/about'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'E-commerce App', root_path, class:"navbar-brand"  %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <li class="nav-item">
        	<%= link_to 'About Us', home_about_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
        	<%= link_to 'Customers', customers_path, class:"nav-link" %>
        </li>
        
        <li class="nav-item">
        	<%= link_to 'Add Customers', new_customer_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Orders', orders_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Add Orders', new_order_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Products', products_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Add Products', new_product_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Address', addresses_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Add Address', new_address_path, class:"nav-link" %>
        </li>

      </ul>
      
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>Get to know about store</h1>
<p>Store is the new online e-commerce store a continuously envolving shopping centre online. Just like inany shopping centre there is always something fresh and exciting.</p>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

This site is developed by using Ruby language and Rails framework.

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<h1>Welcome to E-commerce App</h1>
<body>
<%= image_tag("ecomm.jpg", width: '900px', height: '400px')%>
<br>
Ecommerce is the buying and selling of goods and services over the Internet. It is conducted over computers, tablets, smartphones, and other smart devices. Almost anything can be purchased through ecommerce today.
</body>
</html>